VIDEOSRC="libcamerasrc ! videoscale ! videoconvert ! videobalance saturation=1.5 ! videorate drop-only=true skip-to-first=true"
SPLASHSRC="videotestsrc num-buffers=1 pattern=black ! imagefreeze num-buffers=4 ! videoscale ! videoconvert"
FORMAT=NV12
WIDTH=1280
HEIGHT=720
FRAMERATE=30/1
CARD_LABEL="Hardware ISP Camera"
